apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "terraform-smoketests.fullname" . }}
  labels:
    {{- include "terraform-smoketests.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 28800 # (8 hours)  see https://github.com/kubernetes/kubernetes/issues/89657
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "terraform-smoketests.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "terraform-smoketests.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'pytest -s -v --cloudProvider {{ .Values.cluster.cloudProvider | quote }} --account {{ .Values.cluster.account | quote }} --region {{ .Values.cluster.region | quote }} --name {{ .Values.cluster.name | quote }}']
          env:
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: CLOUD_PROVIDER
              value: {{ .Values.cluster.cloudProvider | quote }}
          envFrom:
            - configMapRef:
                name: ipa-cluster-configuration  
            - configMapRef:
                name: terraform-variables
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
             
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
