- id: terraform-variables
  args: []
  description: Generate terraform configmap from the variables
  entry: generate-variables
#  files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
  language: script
  name: Terraform Variables
  require_serial: true
