#!/usr/bin/env python3

import os
import hcl2
import json

vars = {}
var_rows = ""

with open('variables.tf', 'r') as file: 
    for var in hcl2.load(file)['variable']:
       for var_name in var:
        print(var_name)
        data = var[var_name]
        if data.get('sensitive', False):
           continue
        vars[var_name] = data
    
    for var_name, var in vars.items():
       #print(var_name)
       #print(json.dumps(var))
       var_rows += f"    {var_name} = jsonencode({json.dumps(var)})\n"

config_map = f"""resource "kubernetes_config_map" "terraform-variables" {{
  depends_on = [null_resource.sleep-5-minutes]
  metadata {{
    name = "terraform-variables"
  }}
  data = {{
{var_rows}
  }}
}}
"""

with open("tf-smoketest-variables.tf", "w") as cm:
   cm.write(config_map)

print(config_map)


        
 