#!/bin/bash
echo "Version 1"

hcl2tojson variables.tf > .tf_vars.json

terraform_configmap_file="tf-smoketest-variables.tf"

echo 'resource "kubernetes_config_map" "terraform-variables" {' > ${terraform_configmap_file}
echo '  depends_on = [null_resource.sleep-5-minutes]' >> ${terraform_configmap_file}
echo '  metadata {' >> ${terraform_configmap_file}
echo '    name = "terraform-variables"' >> ${terraform_configmap_file}
echo '  }' >> ${terraform_configmap_file}
echo '  data = {' >> ${terraform_configmap_file}

cat .tf_vars.json|jq -r '.variable[] | keys[]' | while read name ; do
    echo "    $name = \"\${var.$name}\"" >> ${terraform_configmap_file}
done


echo '  }' >> ${terraform_configmap_file}
echo '}' >> ${terraform_configmap_file}



